### ISSUE TITLE
Add version requirements

### ISSUE THREAD

**Issue by sheriffderek** [maxwondercorn/ember-cli-barcode#1]
What versions of Ember will this work with?

I noticed this SO questions - and was going to point them to an answer.

https://stackoverflow.com/questions/48839048/how-to-integrate-other-ember-app-to-existing-project

**Comment by maxwondercorn** [comment]
Good point/question.  Testing is 2.12 forward and it should work backwards to 2.4.  I need to add tests for 3.0, so I add more versions to put a definitive answer in the readme.

**Comment by maxwondercorn** [comment]
Thanks again for the callout.  Testing now goes back to LTS 2.4 and the README has been updated with supported ember versions
