### ISSUE TITLE
Height not working anymore (correctly)

### ISSUE THREAD

**Issue by bmaehr** [maxwondercorn/ember-cli-barcode#15]
At version 0.3.4 I have used
`{{bar-code value='07885' height=70 width=2}} `
which did render the barcode like expected.
After updating to 0.3.6 (and 0.3.7) the barcode is much higher.

**Comment by maxwondercorn** [comment]
v3.5 bumped ember to 3.4.3, v3.6 bumped ember to 3.8.2, v3.7 was just doc updates. So it may be related to the ember change.  I don't think the jsbacode version was bumped but I need to verify.

I test back to ember 2.4 but I only test that the correct barcodes are generated, not other characteristics.

Two questions. What ember version are you using and does the height parameter change the height if you change the value?

**Comment by bmaehr** [comment]
We are using ember 2.18
With 0.3.4 the height changes the height (70 makes it perhaps 25% lower), with 0.3.6 it has no effect anymore.

**Comment by maxwondercorn** [comment]
I built a demo 2.18 app and I don't see any differences between barcode sizes and ember versions.  

The jsbacode dependency version was changed in Oct 2018 so that is not contributing to the issue. Have you tried the v3.5 version, which is ember 3.4

BTW, with height=70 the barcodes I generated are consistently 112px high

**Comment by bmaehr** [comment]
Same problem with 0.3.5.
With 0.3.4 and height=70 the bars of the barcode are exactly 70px high for me: 

```
<svg xmlns="http://www.w3.org/2000/svg" id="ember754" class="ember-view" width="178px" height="112px" x="0px" y="0px" viewBox="0 0 178 112" version="1.1" style="transform: translate(0,0)" aria-labelledby="title">
  <rect x="0" y="0" width="178" height="112" style="fill:#ffffff;"/>
  <g transform="translate(10, 10)" style="fill:#000000;">
    <rect x="0" y="0" width="4" height="70"/>
    <rect x="6" y="0" width="2" height="70"/>
    <rect x="12" y="0" width="6" height="70"/>
    <rect x="22" y="0" width="2" height="70"/>
    <rect x="28" y="0" width="4" height="70"/>
    <rect x="38" y="0" width="2" height="70"/>
    <rect x="44" y="0" width="8" height="70"/>
    <rect x="56" y="0" width="2" height="70"/>
    <rect x="62" y="0" width="2" height="70"/>
    <rect x="66" y="0" width="6" height="70"/>
    <rect x="74" y="0" width="2" height="70"/>
    <rect x="78" y="0" width="8" height="70"/>
    <rect x="88" y="0" width="4" height="70"/>
    <rect x="94" y="0" width="6" height="70"/>
    <rect x="104" y="0" width="2" height="70"/>
    <rect x="110" y="0" width="6" height="70"/>
    <rect x="118" y="0" width="4" height="70"/>
    <rect x="124" y="0" width="2" height="70"/>
    <rect x="132" y="0" width="4" height="70"/>
    <rect x="142" y="0" width="6" height="70"/>
    <rect x="150" y="0" width="2" height="70"/>
    <rect x="154" y="0" width="4" height="70"/>
    <text style="font: 20px monospace" text-anchor="middle" x="79" y="92">07885</text>
  </g>
  <title>Barcode value 07885</title>
</svg>
``` 

With 0.3.5 and independent of height the bars of the barcode are 100px high for me:

```
<svg xmlns="http://www.w3.org/2000/svg" id="ember754" class="ember-view" width="178px" height="142px" x="0px" y="0px" viewBox="0 0 178 142" version="1.1" style="transform: translate(0,0)" aria-labelledby="title">
  <rect x="0" y="0" width="178" height="142" style="fill:#ffffff;"/>
  <g transform="translate(10, 10)" style="fill:#000000;">
    <rect x="0" y="0" width="4" height="100"/>
    <rect x="6" y="0" width="2" height="100"/>
    <rect x="12" y="0" width="6" height="100"/>
    <rect x="22" y="0" width="2" height="100"/>
    <rect x="28" y="0" width="4" height="100"/>
    <rect x="38" y="0" width="2" height="100"/>
    <rect x="44" y="0" width="8" height="100"/>
    <rect x="56" y="0" width="2" height="100"/>
    <rect x="62" y="0" width="2" height="100"/>
    <rect x="66" y="0" width="6" height="100"/>
    <rect x="74" y="0" width="2" height="100"/>
    <rect x="78" y="0" width="8" height="100"/>
    <rect x="88" y="0" width="4" height="100"/>
    <rect x="94" y="0" width="6" height="100"/>
    <rect x="104" y="0" width="2" height="100"/>
    <rect x="110" y="0" width="6" height="100"/>
    <rect x="118" y="0" width="4" height="100"/>
    <rect x="124" y="0" width="2" height="100"/>
    <rect x="132" y="0" width="4" height="100"/>
    <rect x="142" y="0" width="6" height="100"/>
    <rect x="150" y="0" width="2" height="100"/>
    <rect x="154" y="0" width="4" height="100"/>
    <text style="font: 20px monospace" text-anchor="middle" x="79" y="122">07885</text>
  </g>
  <title>Barcode value 07885</title>
</svg>
```

**Comment by maxwondercorn** [comment]
I've mocked several different scenarios of Ember and  addon versions without duplicating the issue.  The only real change between work and not working addon versions is the Ember version upgrades.

Ember has always been very good about isolating app versions and addon versions so I have a hard time believing this is the underlying issue.

My suggestion would be to stay with v0.3.4 or adjust your height to match what you need in later versions.  There isn't any functional changes after 0.3.4 and I don't anticipate any going forward. 

I'm going to leave this issue open in case new info becomes available or someone lurking might have an idea why the issue occurs.

**Comment by bmaehr** [comment]
Thank you for your resarch!

**Comment by maxwondercorn** [comment]
Closed due to no further actiion
