### ISSUE TITLE
Download Button

### ISSUE THREAD

**Issue by designers-prescription** [maxwondercorn/ember-cli-barcode#88]
Can you please suggest how to add a download button along with the options for "SVG, PNG, JPG"?

**Comment by maxwondercorn** [comment]
@designers-prescription  

Not sure you wanted to download all three or just selected files.  You use a `canvas` element to download a `jpeg` or `png`.  To download a `svg` you have to use the `svg` element. Example below.

Use two bar code components with the same `value`.  The `canvas` barcode is displayed.  The `svg` barcode is hidden and only used for downloading `svg` files.

```hbs
{{!-- download.hbs --}}
 <BarCode @value='1234' @tagName='canvas' />
 <BarCode @value='1234' @tagName='svg' hidden />

{{!-- select fileType to download --}}

<button {{on 'click' (fn this.download "selected fileType")}}>
  Download {{fileType}}
</button>
```

Method to download selected file type.  Example assumes `png` was selected
```js
// download.js
@action 
download(fileType) {
  const canv = document.getElementsByTagName('canvas')[0];
  const png = canv.toDataURL('image/png');
  const jpeg = canv.toDataURL('image/jpeg');

  // https://stackoverflow.com/questions/23218174/how-do-i-save-export-an-svg-file-after-creating-an-svg-with-d3-js-ie-safari-an
  const svg = document.getElementsByTagName('svg')[0].outerHTML;
  const svgBlob = new Blob([svg], { type: 'image/svg+xml;charset=utf-8' });
  const svgUrl = URL.createObjectURL(svgBlob);

  const a = document.createElement('a');

  // Determine file type, set href and download name...

  // Pretend png file type was selected
  a.href = png;
  a.download = 'image.png';

  a.click();
  a.remove();

  if (fileType == 'svg') URL.revokeObjectURL(svgUrl);
}
```

I've looked for a way of downloading all three but have not had the time to investigate them. Some links that I've found:

* https://medium.com/twodigits/multi-file-download-using-javascript-9b0b8a14639b
* https://stackoverflow.com/questions/18451856/how-can-i-let-a-user-download-multiple-files-when-a-button-is-clicked
* [jszip](https://stuk.github.io/jszip/) - quickly tried this but `ember-auto-import` doesn't seem to like it  :shrug:
* Also found references to `FileSaver.js`

I'm will be adding a downloading example to the demo and will try to include downloading all files in the example.

**Comment by maxwondercorn** [comment]
See basic download example in demo
